### ISSUE TITLE
Upgrading to L9 - Illuminate\Support

### ISSUE THREAD

**Issue by latwelve** [mvdnbrk/laravel-postmark-webhooks#14]
Hey - thanks for this package I've been using it flawlessly for sometime now.
I've just come to upgrade to L9 from L8 and I have a conflict issue in composer:

  laravel/framework replaces illuminate/support and thus cannot coexist with it. 

Are there any plans to support L9 with this package? or are you open to PR's or should I migrate away from this package if its no longer maintained?

Thanks a mil
Alex

**Comment by mvdnbrk** [comment]
Hi, don't have much time right now.

Could you submit a PR to fix it?

**Comment by latwelve** [comment]
Hey - I don't actually know how but I'm happy to take a look. 

I was hoping I'd find something obvious in other packages that have upgraded to support L9 but haven't spotted anything clear yet.

**Comment by mvdnbrk** [comment]
Thanks!

The tests should also be updates in the tests.yml file in the `.github/workflows` folder.

**Comment by latwelve** [comment]
Oh thanks - I hadn't spotted that - sorry I made 2 pull requests... I'm assuming thats a bit dumb of me!

**Comment by mvdnbrk** [comment]
You can make changes to your first PR and push them to the same PR.

**Comment by latwelve** [comment]
Hey sorry for the slow reply - Thanks for the pointer - I've done that :)

**Comment by mvdnbrk** [comment]
Closing this issue while there is a PR for this. See PR #17
